# Generated by Django 3.1.4 on 2026-06-23 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_padraosemanal'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariodisponivel',
            name='aluno_agendado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monitorias_agendadas', to=settings.AUTH_USER_MODEL, verbose_name='Aluno Agendado'),
        ),
    ]
