# Generated by Django 3.1.4 on 2026-06-23 15:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_horariodisponivel_aluno_agendado'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='turmas_aluno', to=settings.AUTH_USER_MODEL, verbose_name='Alunos Vinculados'),
        ),
        migrations.AddField(
            model_name='turma',
            name='monitores',
            field=models.ManyToManyField(blank=True, related_name='turmas_monitor', to=settings.AUTH_USER_MODEL, verbose_name='Monitores Vinculados'),
        ),
        migrations.AddField(
            model_name='turma',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='turmas_prof', to=settings.AUTH_USER_MODEL, verbose_name='Professores Vinculados'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='professor',
            field=models.ForeignKey(help_text='Professor principal/responsável pela criação da turma', on_delete=django.db.models.deletion.PROTECT, related_name='turmas_ministradas', to=settings.AUTH_USER_MODEL),
        ),
    ]
