# Generated by Django 3.1.4 on 2026-06-23 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20260623_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariodisponivel',
            name='status',
            field=models.CharField(choices=[('VERDE', 'Disponível (Instantâneo)'), ('AMARELO', 'Disponível (Requer Aprovação)'), ('LARANJA', 'Solicitação Pendente'), ('VERMELHO', 'Ocupado / Confirmado')], default='VERDE', max_length=20),
        ),
    ]
