# Generated by Django 3.1.4 on 2026-06-25 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20260623_1324'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monitoria',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='aluno_monitor',
        ),
        migrations.RemoveField(
            model_name='monitoria',
            name='turma',
        ),
        migrations.RemoveField(
            model_name='notificacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Agendamento',
        ),
        migrations.DeleteModel(
            name='Monitoria',
        ),
        migrations.DeleteModel(
            name='Notificacao',
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
