/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.telas;
import backend.backend.entities.Emprestimo;
import backend.backend.entities.Livro;
import backend.backend.entities.Usuario;
import backend.backend.repositories.UsuarioRepository;
import backend.backend.repositories.LivroRepository;
import backend.backend.repositories.EmprestimoRepository;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author luanllp
 */
public class JanelaRealizarEmprestimo extends javax.swing.JFrame {
    private final UsuarioRepository usuarioRepo;
    private final LivroRepository livroRepo;
    private final EmprestimoRepository emprestimoRepo;

    public JanelaRealizarEmprestimo(
        UsuarioRepository usuarioRepo,
        LivroRepository livroRepo,
        EmprestimoRepository emprestimoRepo) {

        initComponents();
        setLocationRelativeTo(null);
        this.usuarioRepo = usuarioRepo;
        this.livroRepo = livroRepo;
        this.emprestimoRepo = emprestimoRepo;

        carregarUsuarios();
        carregarLivrosDisponiveis();
    }

    private void carregarUsuarios() {
        List<Usuario> usuarios = usuarioRepo.findAll();
        comboUsuarios.removeAllItems();
        for (Usuario usuario : usuarios) {
            comboUsuarios.addItem(usuario);
        }
    }

    private void carregarLivrosDisponiveis() {
        List<Livro> livrosDisponiveis = livroRepo.findAll().stream().filter(livro -> livro.isDisponivel()).toList();
        comboLivros.removeAllItems();
        for (Livro livro : livrosDisponiveis) {
            comboLivros.addItem(livro);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboUsuarios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        comboLivros = new javax.swing.JComboBox<>();
        botaoConfirmar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Empréstimo");

        jLabel1.setText("Selecione o Utilizador:");

        jLabel2.setText("Selecione o Livro Disponível:");

        botaoConfirmar.setText("Confirmar Empréstimo");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboUsuarios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboLivros, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(botaoConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboLivros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(botaoConfirmar)
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Usuario usuarioSelecionado = (Usuario) comboUsuarios.getSelectedItem();
    Livro livroSelecionado = (Livro) comboLivros.getSelectedItem();

    if (usuarioSelecionado == null || livroSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um utilizador e um livro.", "Seleção Inválida", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int resposta = JOptionPane.showConfirmDialog(
        this,
        "Confirma o empréstimo do livro '" + livroSelecionado.getTitulo() + "' para o utilizador '" + usuarioSelecionado.getNome() + "'?",
        "Confirmar Empréstimo",
        JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            Emprestimo novoEmprestimo = new Emprestimo();
            novoEmprestimo.setUsuario(usuarioSelecionado);
            novoEmprestimo.setLivro(livroSelecionado);
            novoEmprestimo.setDataEmprestimo(java.time.LocalDate.now()); 
            novoEmprestimo.setDataDevolucaoPrevista(java.time.LocalDate.now().plusWeeks(2)); 

            livroSelecionado.setDisponivel(false);

            this.emprestimoRepo.save(novoEmprestimo); 
            this.livroRepo.save(livroSelecionado);   

            JOptionPane.showMessageDialog(this, "Empréstimo realizado com sucesso!");

            carregarLivrosDisponiveis(); 
            this.dispose(); 

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao realizar o empréstimo: " + e.getMessage(), "Erro de Base de Dados", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace(); 
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JComboBox<Livro> comboLivros;
    private javax.swing.JComboBox<Usuario> comboUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
