/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.telas;
import backend.backend.BackendApplication;
import backend.backend.repositories.EmprestimoRepository;
import backend.backend.repositories.LivroRepository;
import backend.backend.repositories.UsuarioRepository;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.springframework.context.ConfigurableApplicationContext;


/**
 *
 * @author luanllp
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    private static LivroRepository livroRepository;
    private static UsuarioRepository usuarioRepository;
    private static EmprestimoRepository emprestimoRepository;
    /**
     * Creates new form JanelaPrincipal
     */
    public JanelaPrincipal() {
        initComponents();
        try {
        javax.swing.ImageIcon logoOriginal = new javax.swing.ImageIcon(getClass().getResource("/logo.png"));

        javax.swing.ImageIcon logoRedimensionado = redimensionarIcone(logoOriginal, 300, 300);

        labelLogo.setIcon(logoRedimensionado);

        } catch (Exception e) {
            System.out.println("Erro ao carregar a imagem do logo: " + e.getMessage());
            labelLogo.setText("Logo não encontrado");
        }
        java.awt.Font fonteMenu = new java.awt.Font("SansSerif", java.awt.Font.PLAIN, 16);

        for (int i = 0; i < barraDeMenu.getMenuCount(); i++) {
            javax.swing.JMenu menu = barraDeMenu.getMenu(i);
            menu.setFont(fonteMenu);
    }
    }
    private javax.swing.ImageIcon redimensionarIcone(javax.swing.ImageIcon iconeOriginal, int largura, int altura) {
        java.awt.Image imagemOriginal = iconeOriginal.getImage();
        java.awt.Image imagemRedimensionada = imagemOriginal.getScaledInstance(largura, altura, java.awt.Image.SCALE_SMOOTH);
        return new javax.swing.ImageIcon(imagemRedimensionada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogo = new javax.swing.JLabel();
        barraDeMenu = new javax.swing.JMenuBar();
        menuEmprestimos = new javax.swing.JMenu();
        itemNovoEmprestimo = new javax.swing.JMenuItem();
        itemDevolucao = new javax.swing.JMenuItem();
        itemConsultarEmprestimos = new javax.swing.JMenuItem();
        menuLivros = new javax.swing.JMenu();
        itemCadastrarLivro = new javax.swing.JMenuItem();
        itemGerenciarLivros = new javax.swing.JMenuItem();
        menuUsuarios = new javax.swing.JMenu();
        itemCadastrarUsuario = new javax.swing.JMenuItem();
        itemGerenciarUsuarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bibliotecão do Luão e do João");

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(labelLogo, java.awt.BorderLayout.CENTER);

        menuEmprestimos.setText("Emprestimos");

        itemNovoEmprestimo.setText("Novo");
        itemNovoEmprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovoEmprestimoActionPerformed(evt);
            }
        });
        menuEmprestimos.add(itemNovoEmprestimo);

        itemDevolucao.setText("Devolução");
        itemDevolucao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemDevolucaoActionPerformed(evt);
            }
        });
        menuEmprestimos.add(itemDevolucao);

        itemConsultarEmprestimos.setText("Consultar");
        itemConsultarEmprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarEmprestimosActionPerformed(evt);
            }
        });
        menuEmprestimos.add(itemConsultarEmprestimos);

        barraDeMenu.add(menuEmprestimos);

        menuLivros.setText("Livros");

        itemCadastrarLivro.setText("Cadastrar");
        itemCadastrarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarLivroActionPerformed(evt);
            }
        });
        menuLivros.add(itemCadastrarLivro);

        itemGerenciarLivros.setText("Consultar");
        itemGerenciarLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGerenciarLivrosActionPerformed(evt);
            }
        });
        menuLivros.add(itemGerenciarLivros);

        barraDeMenu.add(menuLivros);

        menuUsuarios.setText("Usuários");
        menuUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUsuariosActionPerformed(evt);
            }
        });

        itemCadastrarUsuario.setText("Cadastrar");
        itemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemCadastrarUsuarioActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemCadastrarUsuario);

        itemGerenciarUsuarios.setText("Consultar");
        itemGerenciarUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGerenciarUsuariosActionPerformed(evt);
            }
        });
        menuUsuarios.add(itemGerenciarUsuarios);

        barraDeMenu.add(menuUsuarios);

        setJMenuBar(barraDeMenu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemGerenciarLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarLivrosActionPerformed
        JanelaGerenciarLivros telaDeLivros = new JanelaGerenciarLivros(livroRepository);
        telaDeLivros.setVisible(true);      
    }//GEN-LAST:event_itemGerenciarLivrosActionPerformed

    private void itemCadastrarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarLivroActionPerformed
    JanelaCadastrarLivro telaDeCadastro = new JanelaCadastrarLivro(livroRepository);
    telaDeCadastro.setVisible(true);
    }//GEN-LAST:event_itemCadastrarLivroActionPerformed

    private void menuUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUsuariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuUsuariosActionPerformed

    private void itemGerenciarUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGerenciarUsuariosActionPerformed
        JanelaGerenciarUsuarios telaDeUsuarios = new JanelaGerenciarUsuarios(usuarioRepository);
        telaDeUsuarios.setVisible(true);              // TODO add your handling code here:
    }//GEN-LAST:event_itemGerenciarUsuariosActionPerformed

    private void itemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemCadastrarUsuarioActionPerformed
        JanelaCadastrarUsuario telaCadastroUsuario = new JanelaCadastrarUsuario(usuarioRepository);
        telaCadastroUsuario.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemCadastrarUsuarioActionPerformed

    private void itemNovoEmprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoEmprestimoActionPerformed
        JanelaRealizarEmprestimo telaEmprestimo = new JanelaRealizarEmprestimo(
            usuarioRepository,
            livroRepository,
            emprestimoRepository
        );
        telaEmprestimo.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemNovoEmprestimoActionPerformed

    private void itemDevolucaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemDevolucaoActionPerformed
    JanelaDevolucao telaDevolucao = new JanelaDevolucao(
    livroRepository,
    emprestimoRepository
    );
    telaDevolucao.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemDevolucaoActionPerformed

    private void itemConsultarEmprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarEmprestimosActionPerformed
    JanelaConsultarEmprestimos telaConsulta = new JanelaConsultarEmprestimos(emprestimoRepository);
    telaConsulta.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarEmprestimosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

    SpringApplicationBuilder builder = new SpringApplicationBuilder(BackendApplication.class);
    builder.headless(false);
    ConfigurableApplicationContext context = builder.run(args);

    livroRepository = context.getBean(LivroRepository.class);
    usuarioRepository = context.getBean(UsuarioRepository.class);
    emprestimoRepository = context.getBean(EmprestimoRepository.class);


    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(JanelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        JanelaPrincipal janela = new JanelaPrincipal();
        janela.setExtendedState(javax.swing.JFrame.MAXIMIZED_BOTH);
        janela.setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem itemCadastrarLivro;
    private javax.swing.JMenuItem itemCadastrarUsuario;
    private javax.swing.JMenuItem itemConsultarEmprestimos;
    private javax.swing.JMenuItem itemDevolucao;
    private javax.swing.JMenuItem itemGerenciarLivros;
    private javax.swing.JMenuItem itemGerenciarUsuarios;
    private javax.swing.JMenuItem itemNovoEmprestimo;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JMenu menuEmprestimos;
    private javax.swing.JMenu menuLivros;
    private javax.swing.JMenu menuUsuarios;
    // End of variables declaration//GEN-END:variables
}
