/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.telas;
import backend.backend.entities.Emprestimo;
import backend.backend.repositories.EmprestimoRepository;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author luanllp
 */
public class JanelaConsultarEmprestimos extends javax.swing.JFrame {
    private final EmprestimoRepository emprestimoRepo;
    private DefaultTableModel modeloTabela;
    public JanelaConsultarEmprestimos(EmprestimoRepository emprestimoRepo) {
        initComponents();
        setLocationRelativeTo(null);
        this.emprestimoRepo = emprestimoRepo;
        configurarTabela();
        carregarDadosTabela();
    }
    
    private void configurarTabela() {
        modeloTabela = new DefaultTableModel();
        modeloTabela.addColumn("ID Empréstimo");
        modeloTabela.addColumn("Livro Emprestado");
        modeloTabela.addColumn("Usuário");
        modeloTabela.addColumn("Data do Empréstimo");
        modeloTabela.addColumn("Devolução Prevista");
        tabelaEmprestimos.setModel(modeloTabela);
    }

    private void carregarDadosTabela() {
        modeloTabela.setRowCount(0);
        List<Emprestimo> emprestimos = this.emprestimoRepo.findAll();
        
        for (Emprestimo emprestimo : emprestimos) {
            modeloTabela.addRow(new Object[]{
                emprestimo.getId(),
                emprestimo.getLivro().getTitulo(),
                emprestimo.getUsuario().getNome(),
                emprestimo.getDataEmprestimo(),
                emprestimo.getDataDevolucaoPrevista()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEmprestimos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consultar Empréstimos");

        tabelaEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaEmprestimos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaEmprestimos;
    // End of variables declaration//GEN-END:variables
}
