/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontend.telas;
import backend.backend.entities.Emprestimo;
import backend.backend.entities.Livro;
import backend.backend.repositories.LivroRepository;
import backend.backend.repositories.EmprestimoRepository;
import java.util.List;
import javax.swing.JOptionPane;
/**
 *
 * @author luanllp
 */
public class JanelaDevolucao extends javax.swing.JFrame {
    private final LivroRepository livroRepo;
    private final EmprestimoRepository emprestimoRepo;

    public JanelaDevolucao(LivroRepository livroRepo, EmprestimoRepository emprestimoRepo) {
        initComponents();
        setLocationRelativeTo(null);
        this.livroRepo = livroRepo;
        this.emprestimoRepo = emprestimoRepo;
        carregarEmprestimos();
    }
    
    private void carregarEmprestimos() {
    List<Emprestimo> emprestimos = emprestimoRepo.findAll();
    comboEmprestimos.removeAllItems();
    for (Emprestimo emprestimo : emprestimos) {
        comboEmprestimos.addItem(emprestimo);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        comboEmprestimos = new javax.swing.JComboBox<>();
        botaoDevolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Devolução");

        jLabel1.setText(" Selecione o Empréstimo a ser Devolvido:");

        botaoDevolver.setText("Confirmar Devolução");
        botaoDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(botaoDevolver)
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboEmprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(botaoDevolver)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDevolverActionPerformed
    Emprestimo emprestimoSelecionado = (Emprestimo) comboEmprestimos.getSelectedItem();

    if (emprestimoSelecionado == null) {
        JOptionPane.showMessageDialog(this, "Por favor, selecione um empréstimo para devolver.", "Nenhuma Seleção", JOptionPane.WARNING_MESSAGE);
        return; 
    }

    int resposta = JOptionPane.showConfirmDialog(
        this,
        "Confirma a devolução do livro '" + emprestimoSelecionado.getLivro().getTitulo() + "'?",
        "Confirmar Devolução",
        JOptionPane.YES_NO_OPTION
    );

    if (resposta == JOptionPane.YES_OPTION) {
        try {
            Livro livroParaDevolver = emprestimoSelecionado.getLivro();
            
            livroParaDevolver.setDisponivel(true);
            
            this.livroRepo.save(livroParaDevolver);
            
            this.emprestimoRepo.delete(emprestimoSelecionado);

            JOptionPane.showMessageDialog(this, "Devolução registada com sucesso!");

            carregarEmprestimos();
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao registar a devolução: " + e.getMessage(), "Erro de Base de Dados", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDevolverActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDevolver;
    private javax.swing.JComboBox<Emprestimo> comboEmprestimos;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
